"""Build data.js for the web app from data/CambodiaPostalCode.csv.

The source CSV has rows where the hierarchy columns are misaligned (e.g. Stung Treng
communes listed under Sihanoukville, district rows placed in the commune column).
Postal codes are structured PPDDCC, so we rebuild the hierarchy from the codes:
  PP0000 -> province, PPDD00 -> district, PPDDCC -> commune.

Usage: python scripts/build_data.py
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "CambodiaPostalCode.csv"
OUT = ROOT / "data.js"

KH_PREFIXES = ["រាជធានី", "ខេត្ត", "ក្រុង", "ស្រុក", "ខណ្ឌ", "ឃុំ", "សង្កាត់"]
EN_PREFIXES = ["Sangkat", "Khan"]
EN_FIXES = {
    "070300": "Chhuk",
    "120000": "Phnom Penh",
    "210300": "Borei Chulsar",
}


def clean(text):
    text = text.replace("​", "").replace("﻿", "")
    text = re.sub(r'"\s*(\S+)\s*"', r'"\1"', text)  # Kaoh Thum " Ka " -> Kaoh Thum "Ka"
    return re.sub(r"\s+", " ", text).strip()


def split_kh(name):
    for p in KH_PREFIXES:
        if name.startswith(p):
            return p, name[len(p):].strip()
    return None, name


def split_en(name):
    for p in EN_PREFIXES:
        if name.startswith(p + " "):
            return p, name[len(p) + 1:].strip()
    return None, name


def level_of(code):
    if code.endswith("0000"):
        return "province"
    if code.endswith("00"):
        return "district"
    return "commune"


def entity_type(level, code, kh_prefix, en_prefix):
    if level == "province":
        return "capital" if code.startswith("12") else "province"
    if level == "district":
        if kh_prefix == "ខណ្ឌ" or en_prefix == "Khan":
            return "khan"
        if kh_prefix == "ក្រុង":
            return "municipality"
        return "district"
    if kh_prefix == "សង្កាត់" or en_prefix == "Sangkat":
        return "sangkat"
    return "commune"


def main():
    entries = {}
    with SRC.open(encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            for prefix in ("Provincial", "District", "Commune"):
                code = row[f"{prefix}_postal_code"].strip().zfill(6)
                if not code.isdigit() or code in entries:
                    continue
                kh_prefix, kh = split_kh(clean(row[f"{prefix}_postalarea_kh"]))
                en_prefix, en = split_en(clean(row[f"{prefix}_postalarea_en"]))
                level = level_of(code)
                entries[code] = {
                    "code": code,
                    "level": level,
                    "type": entity_type(level, code, kh_prefix, en_prefix),
                    "kh": kh,
                    "en": en,
                }

    # Typos in the source file.
    for code, en in EN_FIXES.items():
        if code in entries:
            entries[code]["en"] = en

    items = sorted(entries.values(), key=lambda e: e["code"])
    for e in items:
        e["p"] = e["code"][:2] + "0000"
        e["d"] = e["code"][:4] + "00" if e["level"] != "province" else None

    missing = [e["code"] for e in items
               if e["p"] not in entries or (e["d"] and e["d"] not in entries)]
    if missing:
        print("WARNING: parent missing for", missing)

    OUT.write_text(
        "// Generated by scripts/build_data.py - do not edit by hand.\n"
        "window.POSTAL_DATA = " + json.dumps(items, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    counts = {}
    for e in items:
        counts[e["level"]] = counts.get(e["level"], 0) + 1
    print(f"Wrote {OUT.name}: {len(items)} entries {counts}")


if __name__ == "__main__":
    main()
